
package py.gov.aduana.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviciotereSoap", targetNamespace = "http://aduana.gov.py/webservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiciotereSoap {


    /**
     * 
     * @param autenticacion
     * @param idSofia
     * @return
     *     returns py.gov.aduana.webservices.RetornoAnularLote
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "anularLote", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.AnularLote")
    @ResponseWrapper(localName = "anularLoteResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.AnularLoteResponse")
    public RetornoAnularLote anularLote(
        @WebParam(name = "idSofia", targetNamespace = "")
        String idSofia,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param idLoteRemesa
     * @param autenticacion
     * @return
     *     returns py.gov.aduana.webservices.RetornoConsultaGuia
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaGuia", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaGuia")
    @ResponseWrapper(localName = "consultaGuiaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaGuiaResponse")
    public RetornoConsultaGuia consultaGuia(
        @WebParam(name = "idLoteRemesa", targetNamespace = "")
        String idLoteRemesa,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param manifiesto
     * @param autenticacion
     * @return
     *     returns py.gov.aduana.webservices.RetornoAsignarManifiesto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "asignarManifiesto", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.AsignarManifiesto")
    @ResponseWrapper(localName = "asignarManifiestoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.AsignarManifiestoResponse")
    public RetornoAsignarManifiesto asignarManifiesto(
        @WebParam(name = "manifiesto", targetNamespace = "")
        IdManifiesto manifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fechaHasta
     * @param fechaDesde
     * @param autenticacion
     * @return
     *     returns py.gov.aduana.webservices.RetornoConsultarListaGuias
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaGuias", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaGuias")
    @ResponseWrapper(localName = "consultarListaGuiasResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultarListaGuiasResponse")
    public RetornoConsultarListaGuias consultarListaGuias(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        String fechaHasta,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param factura
     * @param autenticacion
     * @return
     *     returns py.gov.aduana.webservices.Recibo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enviarFactura", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.EnviarFactura")
    @ResponseWrapper(localName = "enviarFacturaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.EnviarFacturaResponse")
    public Recibo enviarFactura(
        @WebParam(name = "factura", targetNamespace = "")
        FacturaPDF factura,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param parametros
     * @return
     *     returns py.gov.aduana.webservices.RetornoConsultaInfoGuias
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaInfoGuias", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaInfoGuias")
    @ResponseWrapper(localName = "consultaInfoGuiasResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaInfoGuiasResponse")
    public RetornoConsultaInfoGuias consultaInfoGuias(
        @WebParam(name = "parametros", targetNamespace = "")
        TereFilterDTO parametros,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param autenticacion
     * @param guia
     * @return
     *     returns py.gov.aduana.webservices.RetornoAgregarGuia
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarGuia", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.AgregarGuia")
    @ResponseWrapper(localName = "agregarGuiaResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.AgregarGuiaResponse")
    public RetornoAgregarGuia agregarGuia(
        @WebParam(name = "guia", targetNamespace = "")
        String guia,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param filtro
     * @param autenticacion
     * @return
     *     returns py.gov.aduana.webservices.RetornoImpresionDSImpuesto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "impresionImpuestoDS", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ImpresionImpuestoDS")
    @ResponseWrapper(localName = "impresionImpuestoDSResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ImpresionImpuestoDSResponse")
    public RetornoImpresionDSImpuesto impresionImpuestoDS(
        @WebParam(name = "filtro", targetNamespace = "")
        FiltroConsultaDSImpuesto filtro,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param fracciones
     * @param autenticacion
     * @return
     *     returns py.gov.aduana.webservices.RetornoModificarFraccionado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarFraccionado", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ModificarFraccionado")
    @ResponseWrapper(localName = "modificarFraccionadoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ModificarFraccionadoResponse")
    public RetornoModificarFraccionado modificarFraccionado(
        @WebParam(name = "fracciones", targetNamespace = "")
        String fracciones,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param manifiesto
     * @param autenticacion
     * @return
     *     returns py.gov.aduana.webservices.RetornoConsultaManifiesto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaManifiesto", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaManifiesto")
    @ResponseWrapper(localName = "consultaManifiestoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.ConsultaManifiestoResponse")
    public RetornoConsultaManifiesto consultaManifiesto(
        @WebParam(name = "manifiesto", targetNamespace = "")
        String manifiesto,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

    /**
     * 
     * @param ingreso
     * @param autenticacion
     * @return
     *     returns py.gov.aduana.webservices.RetornoTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresoDeposito", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDeposito")
    @ResponseWrapper(localName = "ingresoDepositoResponse", targetNamespace = "http://aduana.gov.py/webservices", className = "py.gov.aduana.webservices.IngresoDepositoResponse")
    public RetornoTransaccion ingresoDeposito(
        @WebParam(name = "ingreso", targetNamespace = "")
        String ingreso,
        @WebParam(name = "autenticacion", targetNamespace = "")
        Autenticacion autenticacion);

}
