
package py.gov.aduana.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "serviciotere", targetNamespace = "http://aduana.gov.py/webservices", wsdlLocation = "https://secure.aduana.gov.py/wsdl/tere2/serviciotere")
public class Serviciotere
    extends Service
{

    private final static URL SERVICIOTERE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOTERE_EXCEPTION;
    private final static QName SERVICIOTERE_QNAME = new QName("http://aduana.gov.py/webservices", "serviciotere");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://secure.aduana.gov.py/wsdl/tere2/serviciotere");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOTERE_WSDL_LOCATION = url;
        SERVICIOTERE_EXCEPTION = e;
    }

    public Serviciotere() {
        super(__getWsdlLocation(), SERVICIOTERE_QNAME);
    }

    public Serviciotere(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOTERE_QNAME, features);
    }

    public Serviciotere(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOTERE_QNAME);
    }

    public Serviciotere(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOTERE_QNAME, features);
    }

    public Serviciotere(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Serviciotere(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiciotereSoap
     */
    @WebEndpoint(name = "serviciotereSoap")
    public ServiciotereSoap getServiciotereSoap() {
        return super.getPort(new QName("http://aduana.gov.py/webservices", "serviciotereSoap"), ServiciotereSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiciotereSoap
     */
    @WebEndpoint(name = "serviciotereSoap")
    public ServiciotereSoap getServiciotereSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://aduana.gov.py/webservices", "serviciotereSoap"), ServiciotereSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOTERE_EXCEPTION!= null) {
            throw SERVICIOTERE_EXCEPTION;
        }
        return SERVICIOTERE_WSDL_LOCATION;
    }

}
